spring:
  datasource:
    url: jdbc:h2:mem:medicalclinic_dev
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
